### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by tsueken** [tsueken/chat-space2#3]
# IPアドレス
http://54.178.208.245/

**Comment by yasunamiura** [comment]
津江さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

- 文頭にMember:を追加しましょう
[![Image from Gyazo](https://i.gyazo.com/01d43eaed802ac65e58d10f8b6b58baf.png)](https://gyazo.com/01d43eaed802ac65e58d10f8b6b58baf)
見本
[![Image from Gyazo](https://i.gyazo.com/3f705fef067283d5fb721ca49e002a42.png)](https://gyazo.com/3f705fef067283d5fb721ca49e002a42)

修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by yasunamiura** [comment]
再提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！
- グループを作成できるようにしましょう
※現在はエラーが起きてグループ作成後の動作確認することができません
[![Image from Gyazo](https://i.gyazo.com/6fd0ffacdccab98b70e76509604b1fa1.gif)](https://gyazo.com/6fd0ffacdccab98b70e76509604b1fa1)

修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by yasunamiura** [comment]
再度確認したところ、グループ作成して修正が確認できました！大変失礼致しました。
[![Image from Gyazo](https://i.gyazo.com/8a7101391fed2adcf92a829c42326858.png)](https://gyazo.com/8a7101391fed2adcf92a829c42326858)

修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**Comment by tsueken** [comment]
ありがとうございます。
